# Self Attention Implementation

Based on the paper:
Attention Is All You Need (2017)

Objective:
Implement the Self Attention mechanism step by step using NumPy.

In [3]:
import numpy as np

In [2]:
import numpy as np
embeddings = np.array([
    [0.7, 0.8, 0.9],
    [0.4, 0.5, 0.6],
    [0.1, 0.2, 0.3]
])

print("Embedding Matrix:")
print(embeddings)

Embedding Matrix:
[[0.7 0.8 0.9]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]]


## Step 1: Create Query, Key and Value

In a Transformer, each embedding is converted into three vectors:

- Query (Q): What information is this token looking for?
- Key (K): What information does this token contain?
- Value (V): What information should be passed to the next layer?

For this simplified implementation, we will use the embedding matrix itself as Q, K and V.

In [4]:
Q = embeddings

K = embeddings

V = embeddings

print("Query Matrix:")
print(Q)

print("\nKey Matrix:")
print(K)

print("\nValue Matrix:")
print(V)

Query Matrix:
[[0.7 0.8 0.9]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]]

Key Matrix:
[[0.7 0.8 0.9]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]]

Value Matrix:
[[0.7 0.8 0.9]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]]


## Step 2: Calculate Attention Scores

The first step in Self-Attention is to calculate how similar each Query is to every Key.

This is done using Matrix Multiplication:

Attention Scores = Q × Kᵀ

A higher score means the Query and Key are more similar.

In [5]:
scores = np.matmul(Q, K.T)

print("Attention Scores:")
print(scores)

Attention Scores:
[[1.94 1.22 0.5 ]
 [1.22 0.77 0.32]
 [0.5  0.32 0.14]]


## Step 3: Scale the Attention Scores

The dot product values can become very large as the vector dimension increases.

To prevent this, the Transformer divides the attention scores by the square root of the key dimension (√dk).

This helps keep the values stable before applying the Softmax function.

In [6]:
dk = K.shape[1]

scaled_scores = scores / np.sqrt(dk)

print("Scaled Attention Scores:")
print(scaled_scores)

Scaled Attention Scores:
[[1.12005952 0.70436733 0.28867513]
 [0.70436733 0.44455971 0.18475209]
 [0.28867513 0.18475209 0.08082904]]


## Step 4: Apply the Softmax Function

The scaled attention scores are converted into probabilities using the Softmax function.

Softmax ensures that:
- All values lie between 0 and 1.
- The sum of probabilities in each row is equal to 1.

These probabilities are called **Attention Weights**.

In [7]:
def softmax(x):
    exp = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp / np.sum(exp, axis=-1, keepdims=True)

attention_weights = softmax(scaled_scores)

print("Attention Weights:")
print(attention_weights)

Attention Weights:
[[0.47725193 0.31493061 0.20781746]
 [0.42266333 0.32595793 0.25137874]
 [0.36851053 0.33213657 0.29935291]]


## Step 5: Calculate the Final Attention Output

The attention weights are multiplied with the Value matrix.

This produces a new representation for each token by combining information from all the other tokens based on their importance.

In [8]:
output = np.matmul(attention_weights, V)

print("Final Attention Output:")
print(output)

Final Attention Output:
[[0.48083034 0.58083034 0.68083034]
 [0.45138538 0.55138538 0.65138538]
 [0.42074728 0.52074728 0.62074728]]


# Observation

The Self-Attention mechanism works as follows:

1. Convert input tokens into embedding vectors.
2. Create Query (Q), Key (K), and Value (V) matrices.
3. Compute attention scores using Q × Kᵀ.
4. Scale the scores by √dk.
5. Apply the Softmax function to obtain attention weights.
6. Multiply the attention weights with the Value matrix.
7. Generate the final attention output.

This is the core computation introduced in the paper **Attention Is All You Need (2017)**.